# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05d69389ca655f9a5a42d2d099aa33c58a2c122a6743640cea1793ac7f513fc08aafda2020d69771dea0394d895f9b2e752665a264074eab20de634ed66c075

test:
  secret_key_base: 3d1779a69c5f87213d9cf0926beb39203b07ee1b5b36da35320141b9bbc271fcee2def19b3bc19207dce3c68783de6f70964f88429b055a530776490fe0b27eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
